### ISSUE TITLE
django-suit revision template not rendered

### ISSUE THREAD

**Issue by monk8800** [darklow/django-suit#438]
Just installed django revision and trying to integrate it with my django suit installation but i seem to be running into a snag i.e django-suit revision templates are not been picked up. I tried changing the installed_app order and reversion below django-suit. in this case the django suit templates do get picked up but when i click on the recover deleted object button no redirection to the change_list.html happens no errors. Could be my lack of understanding hope someone can point me to the right direction. 

![image 1](https://cloud.githubusercontent.com/assets/2391988/10409431/70343af0-6f52-11e5-8808-e9c77f526bc7.png)

versions

- django-suit==0.2.13
- django-reversion==1.9.3

]

**settings.py**

    INSTALLED_APPS = (
	    'django.contrib.auth',
	    'django.contrib.contenttypes',
	    'django.contrib.sessions',
	    'django.contrib.messages',
	    'django.contrib.staticfiles',
	    'django_extensions',
	    'reversion', # this order works but revision templates used not django-suit
	    'suit',
	    'django.contrib.admin',

    TEMPLATES = [
	    {
		    'BACKEND': 'django.template.backends.django.DjangoTemplates',
		    'DIRS': [os.path.join(PROJECT_ROOT, 'templates')],
		    'APP_DIRS': True,
		    'OPTIONS': {
			    'context_processors': [
				    'django.template.context_processors.debug',
				    'django.template.context_processors.request',
				    'django.contrib.auth.context_processors.auth',
				    'django.contrib.messages.context_processors.messages',
				    'django.core.context_processors.request',
				    'social.apps.django_app.context_processors.backends',
				    'social.apps.django_app.context_processors.login_redirect',
			    ],
	    	},
    	},
    ]

**admin.py**

    from django.contrib import admin
    from geography.models import State
    from django.forms import TextInput, ModelForm
    from reversion.admin import VersionAdmin
    
    class StateForm(ModelForm):
    	state_verbose_name = State._meta.verbose_name
    
    	class Meta:
	    model = State
		    fields = '__all__'
		    	widgets = {
		    		'code': TextInput(attrs={'class': 'input-mini'
				}),
		    }
    
    class StateAdmin(VersionAdmin):
	    form = StateForm
	    search_fields = ('code', 'name')
	    list_display = ('code', 'name')
	    fieldsets = [
	    	(None, {'fields': ['code', 'name']}),
    ]

**Comment by darklow** [comment]
Install latest version. This was fixed by PR: https://github.com/darklow/django-suit/pull/424
```
pip install -U django-suit
```

**Comment by monk8800** [comment]
still facing the same issue even after upgrading
tried reversing my installed apps suit first then reversion correct css rendered but when i do click on the recover deleted items get the below exception 
   'suit',
   'reversion',

![image 1](https://cloud.githubusercontent.com/assets/2391988/10444075/91bdefc4-7194-11e5-8693-ea4b5c5a4fae.png)

**Exception** 

TemplateSyntaxError at /admin/geography/state/recover/
'admin_url' is not a valid tag library: Template library admin_url not found, tried django.templatetags.admin_url,django.contrib.staticfiles.templatetags.admin_url,django_extensions.templatetags.admin_url,suit.templatetags.admin_url,django.contrib.admin.templatetags.admin_url,rest_framework.templatetags.admin_url

**Comment by jpic** [comment]
Same here, there's a typo in the PR, it's not admin_url, but admin_urls !

Maybe some basic tests ie. with django-test-utils would be nice to have.

**Comment by jpic** [comment]
PR #455 fixes it.
